import dotenv from 'dotenv'
dotenv.config()

export const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: parseInt(process.env.PORT || '5003'),
  DATABASE_URL: process.env.DATABASE_URL!,
  JWT_SECRET: process.env.JWT_SECRET!,
  TOKEN_ENCRYPTION_KEY: process.env.TOKEN_ENCRYPTION_KEY!,

  INSTAGRAM_CLIENT_ID: process.env.INSTAGRAM_CLIENT_ID!,
  INSTAGRAM_CLIENT_SECRET: process.env.INSTAGRAM_CLIENT_SECRET!,
  INSTAGRAM_REDIRECT_URI: process.env.INSTAGRAM_REDIRECT_URI!,

  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID!,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET!,
  FACEBOOK_REDIRECT_URI: process.env.FACEBOOK_REDIRECT_URI!,

  TIKTOK_CLIENT_ID: process.env.TIKTOK_CLIENT_ID!,
  TIKTOK_CLIENT_SECRET: process.env.TIKTOK_CLIENT_SECRET!,
  TIKTOK_REDIRECT_URI: process.env.TIKTOK_REDIRECT_URI!,

  LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID!,
  LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET!,
  LINKEDIN_REDIRECT_URI: process.env.LINKEDIN_REDIRECT_URI!,

  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID!,
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET!,
  TWITTER_REDIRECT_URI: process.env.TWITTER_REDIRECT_URI!,

  CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:3000',
}
